services:
  app:
    build: 
      context: ../../
      dockerfile: Dockerfile
    container_name: simulator
    volumes:
      - .:/app/
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
