services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: simulator
    environment:
      KAFKA_BROKER: host.docker.internal:9094
      KAFKA_READ_TOPIC: route.new-direction
      KAFKA_PRODUCE_TOPIC: route.new-position
      KAFKA_CONSUMER_GROUP_ID: simulator
      KAFKA_CLIENT_ID: simulator
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    volumes:
      - .:/app/
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
